import "./globals.css";
import type { Metadata } from "next";
import { headers } from "next/headers";
import Head from "next/head";

import { cookieToInitialState } from "wagmi";

import { config } from "@/config/index";
import AppKitProvider from "@/context/index";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get("cookie"));
  return (
    <html lang="en">
      <body>
        <AppKitProvider initialState={initialState}>{children}</AppKitProvider>
      </body>
    </html>
  );
}
